name: Build Docker Images & Zarf Package

on:
  push:
    branches:
      - '**'       # Run on all branch pushes
    tags:
      - 'v*'       # Also trigger on tags like v1.0.0

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Install Zarf
        uses: zarf-dev/setup-zarf@main
        with:
          version: v0.32.2 # remove to use latest

      - name: Create Zarf package
        run: make package

      - name: Upload binary artifact
        uses: actions/upload-artifact@v4
        with:
          name: zarf-packages
          path: "*.tar.zst"

  release:
    runs-on: ubuntu-latest
    needs: build
    if: startsWith(github.ref, 'refs/tags/')

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Download Zarf package artifacts from build
        uses: actions/download-artifact@v3
        with:
          name: zarf-packages
          path: ./zarf-packages

      - name: Create GitHub release
        id: create_release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload Zarf packages to release
        run: |
          for f in ./zarf-packages/*.tar.zst; do
            gh release upload ${{ github.ref_name }} "$f" --repo ${{ github.repository }} --clobber
          done
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}